modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPL 3.0"
[[mods]]
modId="forgemalilib"
version="0.10.0"
displayName="Forgemalilib"
authors=["Gugle","masa"]
description='''
malilib is a library mod used by masa's LiteLoader mods. It contains some common code previously duplicated in most of the mods, such as multi-key capable keybinds, configuration GUIs etc.
'''
[[dependencies.forgemalilib]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.forgemalilib]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
